export default {
  success: "success",
  error: "error",
  selects: document.querySelectorAll(".form__currency-select"),
  amountInput: document.querySelector("#amount"),
  form: document.querySelector(".form"),
  resultFrom: document.querySelector("#resultFrom"),
  resultTo: document.querySelector("#resultTo"),
  convesionRate: document.querySelector(".form__result-rate"),
  lastUpdate: document.querySelector(".form__result-update"),
  switchBtn: document.querySelector("#switchCurrency"),
  selectFrom: document.querySelector("#from"),
  selectTo: document.querySelector("#to"),
  tabs: document.querySelector(".tabs"),
  currentCurrency: document.querySelector(".currency__single-item"),
  currencyList: document.querySelector(".currency__list"),
};
